### PR TITLE
Restrict manifest v3 to 128.0 (Fixes #280)

### LINKED ISSUE #280: Restrict Manifest V3 uploads to Thunderbird 128.0b1 or later
We are finishing our Manifest V3 support for Thunderbird 128 (code work is done, some patches still have to be reviewed). An add-on using Manifest V3 has to specify that in its manifest:

```
"manifest_version": 3
```

Many interfaces of our Manifest V3 APIs have changed a lot in the last months - and we stated in our documentation, that the MV3 implementation is still changing: https://webextension-api.thunderbird.net/en/latest-mv3/

Manifest V3 add-ons working in Thunderbird 128+ will be partially incompatible to the Manifest V3 implementation of Thunderbird 115 or 102. We should therefore require a `min_strict_version` entry of `128.0a1` or greater (just the major version number needs to be checked to be 128 or greater).

**Edit: The check must be for 128.b01 or later**

I do not know if that information is relevant: Manifest V3 no longer supports the `application` manifest entry, but only `browser_specific_settings`. 

```
{
  "manifest_version": 3,
  "version": "1.0",
  "author": "Thunderbird Team",
  "name": "Message Display Script Example",
  "description": "An extension example how to use message display script",
  "browser_specific_settings": {
    "gecko": {
      "id": "messageDisplayScript@sample.extensions.thunderbird.net",
      "strict_min_version": "128.0a1"
    }
  }
```

### PR DESCRIPTION
**Pull request by MelissaAutumn**
Fixes #280 

This adds two additional checks to our manifest.json parser. 

1. If a manifest.json has `manifest_version: 3`, require that `strict_min_version` exists and is greater than or equal to `128.0b1`.
2. If a manifest.json has `manifest_version: 3` don't allow the `applications` key. 

cc @jobisoft

### CODE REVIEW

**Comment by jobisoft** [comment]
I added 128.0b1 as an actual usable app version:

image

**Comment by Sancus** [comment]
Not sure there is such a thing as "b1" at all? I thought betas had internal version the same as release, intentionally so.

**Comment by jobisoft** [comment]
> Not sure there is such a thing as "b1" at all? I thought betas had internal version the same as release, intentionally so. A letter is only present on Daily versions.

How do we solve this?

In our past communication, we said (as an example) 128.0 is greater than 128.0a1. And indeed, I cannot install an add-on in 128 Daily with `"strict_min_version": "128.0"`.

I can however install an add-on in 127 Beta with `"strict_min_version": "127.0"`. So it appears the order is

*.0a1 < *.0 <= *.0b1 (probably because it is just like *.0)

Is that correct? Based on my test with `"strict_min_version": "127.0"`, we then should be fine with enforcing a min version of `128.0` for Manifest V3, as that will exclude Daily, but include Beta, which is what I want.

Does that sound sensible?

**Comment by MelissaAutumn** [comment]
Its a two second change so let me know if it should be 128!

**Comment by jobisoft** [comment]
> Its a two second change so let me know if it should be 128!

Yes, it must be 128.0 as minimum requirement. Thanks!

**Comment by MelissaAutumn** [comment]
Okay changes are up. Any final reviews before this is good to merge?

**Review by Sancus — APPROVED** [review]
Seems OK to me,

**Comment by MelissaAutumn** [comment]
Will test it on stage, and merge it up after. Thanks!

**Pull request merged**
